name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 


      - name: Initialize Terraform
        run: terraform init

      - name: Format Terraform
        run: terraform fmt

      - name: Plan Terraform Deployment
        run: terraform plan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve

      - name: Wait for 5 minutes before destroying
        run: sleep 300  # 300 seconds = 5 minutes

      - name: Destroy Resources
        run: terraform destroy -auto-approve

